# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!
# Uncomment this line if you're using Swift
use_frameworks!

target 'HATDeX' do
    
    pod 'Alamofire'
    pod 'RealmSwift'
    pod 'SwiftyJSON'
    pod 'FBAnnotationClusteringSwift', git: 'https://github.com/ribl/FBAnnotationClusteringSwift/', branch: 'master'
    pod 'JWTDecode'
    pod 'SwiftyRSA'
    pod 'KeychainSwift'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'BEMCheckBox'
    pod 'zxcvbn-ios'
    pod 'HatForIOS', :git => 'https://github.com/whiteshadow-gr/HatForIOS.git'
    pod 'SwiftLint', '0.21.0'
    pod 'MarkdownView', git: 'https://github.com/keitaoouchi/MarkdownView/', branch: 'master'
    pod 'Haneke'
end

target 'HATDeXTests' do
    
    inherit! :complete
    pod 'Alamofire'
    pod 'RealmSwift'
    pod 'SwiftyJSON'
    pod 'FBAnnotationClusteringSwift', git: 'https://github.com/ribl/FBAnnotationClusteringSwift/', branch: 'master'
    pod 'JWTDecode'
    pod 'SwiftyRSA'
    pod 'KeychainSwift'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'BEMCheckBox'
    pod 'zxcvbn-ios'
    pod 'HatForIOS', :git => 'https://github.com/whiteshadow-gr/HatForIOS.git'
    pod 'Mockingjay'
    pod 'MarkdownView', git: 'https://github.com/keitaoouchi/MarkdownView/', branch: 'master'
    pod 'Haneke'
end

target 'HATDeXUITests' do

    inherit! :complete
    pod 'Alamofire'
    pod 'RealmSwift'
    pod 'SwiftyJSON'
    pod 'FBAnnotationClusteringSwift', git: 'https://github.com/ribl/FBAnnotationClusteringSwift/', branch: 'master'
    pod 'JWTDecode'
    pod 'SwiftyRSA'
    pod 'KeychainSwift'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'BEMCheckBox'
    pod 'zxcvbn-ios'
    pod 'HatForIOS', :git => 'https://github.com/whiteshadow-gr/HatForIOS.git'
    pod 'Mockingjay'
    pod 'MarkdownView', git: 'https://github.com/keitaoouchi/MarkdownView/', branch: 'master'
    pod 'Haneke'
end
